### ISSUE TITLE
HackerNews HTML has changed, API has stopped working

### ISSUE THREAD

**Issue by kseistrup** [karan/HackerNewsAPI#46]
```py
$ python2
Python 2.7.9 (default, Dec 11 2014, 04:42:00) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from hn import HN
>>> hn = HN()
>>> for story in hn.get_stories(story_type='newest', limit=10):
...     pass
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/hn/hn.py", line 145, in get_stories
    stories = self._build_story(all_rows) # get a list of stories on current page
  File "/usr/lib/python2.7/site-packages/hn/hn.py", line 71, in _build_story
    domain = info_cells[2].find('span').string[2:-2] # slice " (abc.com) "
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by lahdo** [comment]
Still not working.

**Comment by fizal619** [comment]
Confirmed still broken. :'(
